spring:
  application:
    name: messenger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns
    username: user326
    password: 1234
#    username: root
#    password:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  upload:
    path: upload

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff

cors:
#  allowed-origins: http://localhost:3000, http://localhost:3001
  allowed-origins: http://3.37.123.45, http://3.37.123.45:3000


